-- Database Table Export for `feasibility_checks`
-- Generated: 2026-06-25 07:00:57
-- DB Name: if0_40845939_clarity_db

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `feasibility_checks`;

CREATE TABLE `feasibility_checks` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `assignment_id` int(11) NOT NULL,
  `site_id` int(11) NOT NULL,
  `no_of_atm` int(11) DEFAULT 0,
  `atm_id_1` varchar(100) DEFAULT NULL,
  `atm_id_2` varchar(100) DEFAULT NULL,
  `atm_id_3` varchar(100) DEFAULT NULL,
  `atm_1_status` varchar(50) DEFAULT NULL,
  `atm_2_status` varchar(50) DEFAULT NULL,
  `atm_3_status` varchar(50) DEFAULT NULL,
  `operator` varchar(100) DEFAULT NULL,
  `signal_status` varchar(50) DEFAULT NULL,
  `operator_2` varchar(100) DEFAULT NULL,
  `signal_status_2` varchar(50) DEFAULT NULL,
  `backroom_network_remark` text DEFAULT NULL,
  `ups_available` varchar(10) DEFAULT NULL,
  `no_of_ups` int(11) DEFAULT NULL,
  `ups_battery_backup` varchar(50) DEFAULT NULL,
  `ups_working_1` varchar(50) DEFAULT NULL,
  `ups_working_2` varchar(50) DEFAULT NULL,
  `ups_working_3` varchar(50) DEFAULT NULL,
  `power_socket_availability` varchar(50) DEFAULT NULL,
  `power_socket_availability_ups` varchar(50) DEFAULT NULL,
  `earthing` varchar(50) DEFAULT NULL,
  `earthing_voltage` varchar(50) DEFAULT NULL,
  `power_fluctuation_en` varchar(50) DEFAULT NULL,
  `power_fluctuation_pe` varchar(50) DEFAULT NULL,
  `power_fluctuation_pn` varchar(50) DEFAULT NULL,
  `frequent_power_cut` varchar(10) DEFAULT NULL,
  `frequent_power_cut_from` time DEFAULT NULL,
  `frequent_power_cut_to` time DEFAULT NULL,
  `frequent_power_cut_remark` text DEFAULT NULL,
  `em_lock_available` varchar(10) DEFAULT NULL,
  `em_lock_password` varchar(100) DEFAULT NULL,
  `password_received` varchar(10) DEFAULT NULL,
  `backroom_key_name` varchar(100) DEFAULT NULL,
  `backroom_key_number` varchar(50) DEFAULT NULL,
  `backroom_key_status` varchar(50) DEFAULT NULL,
  `antenna_routing_detail` text DEFAULT NULL,
  `router_antenna_position` varchar(100) DEFAULT NULL,
  `router_position` varchar(100) DEFAULT NULL,
  `nearest_shop_name` varchar(200) DEFAULT NULL,
  `nearest_shop_number` varchar(50) DEFAULT NULL,
  `nearest_shop_distance` varchar(50) DEFAULT NULL,
  `backroom_disturbing_material` varchar(10) DEFAULT NULL,
  `backroom_disturbing_material_remark` text DEFAULT NULL,
  `remarks` text DEFAULT NULL,
  `backroom_network_snap` varchar(500) DEFAULT NULL,
  `router_antenna_snap` varchar(500) DEFAULT NULL,
  `antenna_routing_snap` varchar(500) DEFAULT NULL,
  `ups_available_snap` varchar(500) DEFAULT NULL,
  `no_of_ups_snap` varchar(500) DEFAULT NULL,
  `ups_working_snap` varchar(500) DEFAULT NULL,
  `power_socket_availability_snap` varchar(500) DEFAULT NULL,
  `earthing_snap` varchar(500) DEFAULT NULL,
  `power_fluctuation_snap` varchar(500) DEFAULT NULL,
  `remarks_snap` varchar(500) DEFAULT NULL,
  `status` enum('active','inactive') DEFAULT 'active',
  `approval_status` enum('pending_contractor_review','contractor_approved','contractor_rejected','adv_approved','adv_rejected') DEFAULT 'pending_contractor_review',
  `created_by` int(11) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_assignment_check` (`assignment_id`),
  KEY `idx_site` (`site_id`),
  KEY `idx_status` (`status`),
  KEY `idx_approval_status` (`approval_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- No data found in `feasibility_checks`

SET FOREIGN_KEY_CHECKS = 1;
