-- Database Table Export for `installations`
-- Generated: 2026-06-25 07:00:57
-- DB Name: if0_40845939_clarity_db

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `installations`;

CREATE TABLE `installations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `site_id` int(11) NOT NULL COMMENT 'Reference to sites table',
  `feasibility_id` int(11) NOT NULL COMMENT 'Reference to feasibility_checks table',
  `initiated_by` int(11) NOT NULL COMMENT 'ADV user who initiated installation',
  `initiated_at` timestamp NOT NULL DEFAULT current_timestamp() COMMENT 'When installation was initiated',
  `contractor_id` int(11) DEFAULT NULL COMMENT 'Contractor company ID for installation',
  `delegated_by` int(11) DEFAULT NULL COMMENT 'ADV user who delegated to contractor',
  `delegated_at` timestamp NULL DEFAULT NULL COMMENT 'When installation was delegated to contractor',
  `assigned_engineer_id` int(11) DEFAULT NULL COMMENT 'Engineer assigned to perform installation',
  `assigned_by` int(11) DEFAULT NULL COMMENT 'Contractor user who assigned the engineer',
  `assigned_at` timestamp NULL DEFAULT NULL COMMENT 'When engineer was assigned',
  `eta_date` date DEFAULT NULL COMMENT 'Estimated Time of Arrival date',
  `eta_submitted_at` timestamp NULL DEFAULT NULL COMMENT 'When ETA was submitted',
  `ada_date` date DEFAULT NULL COMMENT 'Actual Date of Arrival',
  `ada_submitted_at` timestamp NULL DEFAULT NULL COMMENT 'When ADA was submitted',
  `atm_id` varchar(100) NOT NULL COMMENT 'Primary ATM ID',
  `atm_id_2` varchar(100) DEFAULT NULL,
  `atm_id_3` varchar(100) DEFAULT NULL,
  `address` text DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `location` varchar(200) DEFAULT NULL,
  `lho` varchar(100) DEFAULT NULL,
  `state` varchar(100) DEFAULT NULL,
  `atm_working_1` varchar(50) DEFAULT NULL,
  `atm_working_2` varchar(50) DEFAULT NULL,
  `atm_working_3` varchar(50) DEFAULT NULL,
  `vendor_name` varchar(200) DEFAULT NULL,
  `engineer_name` varchar(200) DEFAULT NULL,
  `engineer_number` varchar(50) DEFAULT NULL,
  `router_serial` varchar(100) DEFAULT NULL,
  `router_make` varchar(100) DEFAULT NULL,
  `router_model` varchar(100) DEFAULT NULL,
  `router_fixed` enum('yes','no') DEFAULT NULL,
  `router_fixed_remarks` text DEFAULT NULL,
  `router_fixed_snaps` text DEFAULT NULL,
  `router_status` enum('working','notWorking') DEFAULT NULL,
  `router_status_remarks` text DEFAULT NULL,
  `router_status_snaps` text DEFAULT NULL,
  `adaptor_installed` enum('yes','no') DEFAULT NULL,
  `adaptor_snaps` text DEFAULT NULL,
  `adaptor_status` enum('working','notWorking') DEFAULT NULL,
  `adaptor_status_remarks` text DEFAULT NULL,
  `adaptor_status_snaps` text DEFAULT NULL,
  `lan_cable_installed` enum('yes','no') DEFAULT NULL,
  `lan_cable_install_remark` text DEFAULT NULL,
  `lan_cable_install_snap` text DEFAULT NULL,
  `lan_cable_status` enum('working','notWorking') DEFAULT NULL,
  `lan_cable_status_not_working_reasons` text DEFAULT NULL,
  `lan_cable_status_remark` text DEFAULT NULL,
  `lan_cable_status_snap` text DEFAULT NULL,
  `antenna_installed` enum('yes','no') DEFAULT NULL,
  `antenna_remarks` text DEFAULT NULL,
  `antenna_snaps` text DEFAULT NULL,
  `antenna_status` enum('working','notWorking') DEFAULT NULL,
  `antenna_status_remarks` text DEFAULT NULL,
  `antenna_status_snaps` text DEFAULT NULL,
  `gps_installed` enum('yes','no') DEFAULT NULL,
  `gps_remarks` text DEFAULT NULL,
  `gps_snaps` text DEFAULT NULL,
  `gps_status` enum('working','notWorking') DEFAULT NULL,
  `gps_status_remarks` text DEFAULT NULL,
  `gps_status_snaps` text DEFAULT NULL,
  `wifi_installed` enum('yes','no') DEFAULT NULL,
  `wifi_remarks` text DEFAULT NULL,
  `wifi_snaps` text DEFAULT NULL,
  `wifi_status` enum('working','notWorking') DEFAULT NULL,
  `wifi_status_remarks` text DEFAULT NULL,
  `wifi_status_snaps` text DEFAULT NULL,
  `airtel_sim_installed` enum('yes','no') DEFAULT NULL,
  `airtel_sim_remarks` text DEFAULT NULL,
  `airtel_sim_snaps` text DEFAULT NULL,
  `airtel_sim_status` enum('working','notWorking') DEFAULT NULL,
  `airtel_sim_status_remarks` text DEFAULT NULL,
  `airtel_sim_status_snaps` text DEFAULT NULL,
  `vodafone_sim_installed` enum('yes','no') DEFAULT NULL,
  `vodafone_sim_remarks` text DEFAULT NULL,
  `vodafone_sim_snaps` text DEFAULT NULL,
  `vodafone_sim_status` enum('working','notWorking') DEFAULT NULL,
  `vodafone_sim_status_remarks` text DEFAULT NULL,
  `vodafone_sim_status_snaps` text DEFAULT NULL,
  `jio_sim_installed` enum('yes','no') DEFAULT NULL,
  `jio_sim_remarks` text DEFAULT NULL,
  `jio_sim_snaps` text DEFAULT NULL,
  `jio_sim_status` enum('working','notWorking') DEFAULT NULL,
  `jio_sim_status_remarks` text DEFAULT NULL,
  `jio_sim_status_snaps` text DEFAULT NULL,
  `signature_image` varchar(500) DEFAULT NULL,
  `vendor_stamp` varchar(500) DEFAULT NULL,
  `status` enum('pending_assignment','pending_eta','pending_ada','pending_materials','materials_received','in_progress','submitted','pending_contractor_review','contractor_approved','contractor_rejected','adv_approved','adv_rejected') DEFAULT 'pending_assignment' COMMENT 'Installation workflow status',
  `created_by` int(11) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  `submitted_by` int(11) DEFAULT NULL,
  `submitted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_site_installation` (`site_id`),
  KEY `idx_feasibility` (`feasibility_id`),
  KEY `idx_status` (`status`),
  KEY `idx_initiated_by` (`initiated_by`),
  KEY `idx_created_by` (`created_by`),
  KEY `fk_installations_delegated_by` (`delegated_by`),
  KEY `idx_contractor` (`contractor_id`),
  KEY `fk_installations_assigned_by` (`assigned_by`),
  KEY `idx_assigned_engineer` (`assigned_engineer_id`),
  KEY `idx_eta_date` (`eta_date`),
  KEY `idx_ada_date` (`ada_date`),
  CONSTRAINT `fk_installations_assigned_by` FOREIGN KEY (`assigned_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_installations_assigned_engineer` FOREIGN KEY (`assigned_engineer_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_installations_contractor` FOREIGN KEY (`contractor_id`) REFERENCES `companies` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_installations_delegated_by` FOREIGN KEY (`delegated_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=88426 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- No data found in `installations`

SET FOREIGN_KEY_CHECKS = 1;
