-- Database Table Export for `system_settings`
-- Generated: 2026-06-25 07:00:57
-- DB Name: if0_40845939_clarity_db

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `system_settings`;

CREATE TABLE `system_settings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `category` varchar(50) NOT NULL,
  `setting_key` varchar(100) NOT NULL,
  `setting_value` text DEFAULT NULL,
  `default_value` text DEFAULT NULL,
  `data_type` enum('string','integer','boolean','json') DEFAULT 'string',
  `description` text DEFAULT NULL,
  `validation_rules` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`validation_rules`)),
  `is_required` tinyint(1) DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `setting_key` (`setting_key`),
  KEY `idx_category` (`category`),
  KEY `idx_key` (`setting_key`)
) ENGINE=InnoDB AUTO_INCREMENT=6403 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table `system_settings`
INSERT INTO `system_settings` (`id`, `category`, `setting_key`, `setting_value`, `default_value`, `data_type`, `description`, `validation_rules`, `is_required`, `created_at`, `updated_at`) VALUES ('1', 'General', 'site_name', 'ADVANTAGESB', 'ADV CRM System', 'string', 'The name of the application displayed in the interface', '{\"required\": true, \"min_length\": 3, \"max_length\": 100}', '1', '2026-01-06 08:28:15', '2026-01-06 12:31:21');
INSERT INTO `system_settings` (`id`, `category`, `setting_key`, `setting_value`, `default_value`, `data_type`, `description`, `validation_rules`, `is_required`, `created_at`, `updated_at`) VALUES ('2', 'General', 'default_timezone', 'Asia/Kolkata', 'UTC', 'string', 'Default timezone for the application', '{\"required\": true, \"allowed_values\": [\"UTC\", \"America/New_York\", \"America/Chicago\", \"America/Denver\", \"America/Los_Angeles\", \"Europe/London\", \"Europe/Paris\", \"Asia/Tokyo\", \"Asia/Kolkata\"]}', '1', '2026-01-06 08:28:15', '2026-01-06 12:23:03');
INSERT INTO `system_settings` (`id`, `category`, `setting_key`, `setting_value`, `default_value`, `data_type`, `description`, `validation_rules`, `is_required`, `created_at`, `updated_at`) VALUES ('3', 'General', 'default_language', 'en', 'en', 'string', 'Default language for the application interface', '{\"required\": true, \"allowed_values\": [\"en\", \"es\", \"fr\", \"de\", \"it\", \"pt\", \"ja\", \"zh\", \"hi\"]}', '1', '2026-01-06 08:28:15', '2026-01-06 08:28:15');
INSERT INTO `system_settings` (`id`, `category`, `setting_key`, `setting_value`, `default_value`, `data_type`, `description`, `validation_rules`, `is_required`, `created_at`, `updated_at`) VALUES ('4', 'General', 'date_format', 'Y-m-d', 'Y-m-d', 'string', 'Default date format for displaying dates', '{\"required\": true, \"allowed_values\": [\"Y-m-d\", \"m/d/Y\", \"d/m/Y\", \"d-m-Y\", \"M j, Y\"]}', '1', '2026-01-06 08:28:15', '2026-01-06 08:28:15');
INSERT INTO `system_settings` (`id`, `category`, `setting_key`, `setting_value`, `default_value`, `data_type`, `description`, `validation_rules`, `is_required`, `created_at`, `updated_at`) VALUES ('5', 'General', 'items_per_page', '25', '25', 'integer', 'Default number of items to display per page in lists', '{\"required\": true, \"min_value\": 10, \"max_value\": 100}', '1', '2026-01-06 08:28:15', '2026-01-06 08:28:15');
INSERT INTO `system_settings` (`id`, `category`, `setting_key`, `setting_value`, `default_value`, `data_type`, `description`, `validation_rules`, `is_required`, `created_at`, `updated_at`) VALUES ('6', 'Security', 'session_timeout', '3600', '3600', 'integer', 'Session timeout in seconds (default: 1 hour)', '{\"required\": true, \"min_value\": 300, \"max_value\": 86400}', '1', '2026-01-06 08:28:15', '2026-01-06 08:28:15');
INSERT INTO `system_settings` (`id`, `category`, `setting_key`, `setting_value`, `default_value`, `data_type`, `description`, `validation_rules`, `is_required`, `created_at`, `updated_at`) VALUES ('7', 'Security', 'password_min_length', '8', '8', 'integer', 'Minimum password length requirement', '{\"required\": true, \"min_value\": 6, \"max_value\": 32}', '1', '2026-01-06 08:28:15', '2026-01-06 08:28:15');
INSERT INTO `system_settings` (`id`, `category`, `setting_key`, `setting_value`, `default_value`, `data_type`, `description`, `validation_rules`, `is_required`, `created_at`, `updated_at`) VALUES ('8', 'Security', 'password_require_special', 'true', 'true', 'boolean', 'Require special characters in passwords', '{\"required\": true}', '1', '2026-01-06 08:28:15', '2026-01-06 08:28:15');
INSERT INTO `system_settings` (`id`, `category`, `setting_key`, `setting_value`, `default_value`, `data_type`, `description`, `validation_rules`, `is_required`, `created_at`, `updated_at`) VALUES ('9', 'Security', 'max_login_attempts', '5', '5', 'integer', 'Maximum failed login attempts before account lockout', '{\"required\": true, \"min_value\": 3, \"max_value\": 10}', '1', '2026-01-06 08:28:15', '2026-01-06 08:28:15');
INSERT INTO `system_settings` (`id`, `category`, `setting_key`, `setting_value`, `default_value`, `data_type`, `description`, `validation_rules`, `is_required`, `created_at`, `updated_at`) VALUES ('10', 'Security', 'lockout_duration', '900', '900', 'integer', 'Account lockout duration in seconds (default: 15 minutes)', '{\"required\": true, \"min_value\": 300, \"max_value\": 3600}', '1', '2026-01-06 08:28:15', '2026-01-06 08:28:15');
INSERT INTO `system_settings` (`id`, `category`, `setting_key`, `setting_value`, `default_value`, `data_type`, `description`, `validation_rules`, `is_required`, `created_at`, `updated_at`) VALUES ('11', 'Email', 'smtp_host', '', '', 'string', 'SMTP server hostname', '{\"max_length\": 255}', '0', '2026-01-06 08:28:15', '2026-01-06 08:28:15');
INSERT INTO `system_settings` (`id`, `category`, `setting_key`, `setting_value`, `default_value`, `data_type`, `description`, `validation_rules`, `is_required`, `created_at`, `updated_at`) VALUES ('12', 'Email', 'smtp_port', '587', '587', 'integer', 'SMTP server port', '{\"min_value\": 1, \"max_value\": 65535}', '0', '2026-01-06 08:28:15', '2026-01-06 08:28:15');
INSERT INTO `system_settings` (`id`, `category`, `setting_key`, `setting_value`, `default_value`, `data_type`, `description`, `validation_rules`, `is_required`, `created_at`, `updated_at`) VALUES ('13', 'Email', 'smtp_username', '', '', 'string', 'SMTP authentication username', '{\"max_length\": 255}', '0', '2026-01-06 08:28:15', '2026-01-06 08:28:15');
INSERT INTO `system_settings` (`id`, `category`, `setting_key`, `setting_value`, `default_value`, `data_type`, `description`, `validation_rules`, `is_required`, `created_at`, `updated_at`) VALUES ('14', 'Email', 'smtp_encryption', 'tls', 'tls', 'string', 'SMTP encryption method', '{\"allowed_values\": [\"none\", \"ssl\", \"tls\"]}', '0', '2026-01-06 08:28:15', '2026-01-06 08:28:15');
INSERT INTO `system_settings` (`id`, `category`, `setting_key`, `setting_value`, `default_value`, `data_type`, `description`, `validation_rules`, `is_required`, `created_at`, `updated_at`) VALUES ('15', 'Email', 'from_email', 'noreply@advcrm.local', 'noreply@advcrm.local', 'string', 'Default from email address', '{\"pattern\": \"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$\", \"max_length\": 255}', '0', '2026-01-06 08:28:15', '2026-01-06 08:28:15');
INSERT INTO `system_settings` (`id`, `category`, `setting_key`, `setting_value`, `default_value`, `data_type`, `description`, `validation_rules`, `is_required`, `created_at`, `updated_at`) VALUES ('16', 'Email', 'from_name', 'ADV CRM System', 'ADV CRM System', 'string', 'Default from name for emails', '{\"max_length\": 100}', '0', '2026-01-06 08:28:15', '2026-01-06 08:28:15');
INSERT INTO `system_settings` (`id`, `category`, `setting_key`, `setting_value`, `default_value`, `data_type`, `description`, `validation_rules`, `is_required`, `created_at`, `updated_at`) VALUES ('17', 'Backup', 'backup_enabled', 'true', 'true', 'boolean', 'Enable automatic database backups', '{\"required\": true}', '1', '2026-01-06 08:28:15', '2026-01-06 08:28:15');
INSERT INTO `system_settings` (`id`, `category`, `setting_key`, `setting_value`, `default_value`, `data_type`, `description`, `validation_rules`, `is_required`, `created_at`, `updated_at`) VALUES ('18', 'Backup', 'backup_frequency', 'daily', 'daily', 'string', 'Backup frequency schedule', '{\"required\": true, \"allowed_values\": [\"hourly\", \"daily\", \"weekly\", \"monthly\"]}', '1', '2026-01-06 08:28:15', '2026-01-06 08:28:15');
INSERT INTO `system_settings` (`id`, `category`, `setting_key`, `setting_value`, `default_value`, `data_type`, `description`, `validation_rules`, `is_required`, `created_at`, `updated_at`) VALUES ('19', 'Backup', 'backup_retention_days', '30', '30', 'integer', 'Number of days to retain backup files', '{\"required\": true, \"min_value\": 7, \"max_value\": 365}', '1', '2026-01-06 08:28:16', '2026-01-06 08:28:16');
INSERT INTO `system_settings` (`id`, `category`, `setting_key`, `setting_value`, `default_value`, `data_type`, `description`, `validation_rules`, `is_required`, `created_at`, `updated_at`) VALUES ('20', 'Backup', 'backup_path', './backups/', './backups/', 'string', 'Directory path for storing backup files', '{\"required\": true, \"max_length\": 255}', '1', '2026-01-06 08:28:16', '2026-01-06 08:28:16');
INSERT INTO `system_settings` (`id`, `category`, `setting_key`, `setting_value`, `default_value`, `data_type`, `description`, `validation_rules`, `is_required`, `created_at`, `updated_at`) VALUES ('21', 'Logging', 'log_level', 'INFO', 'INFO', 'string', 'Minimum log level to record', '{\"required\": true, \"allowed_values\": [\"DEBUG\", \"INFO\", \"WARNING\", \"ERROR\", \"CRITICAL\"]}', '1', '2026-01-06 08:28:16', '2026-01-06 08:28:16');
INSERT INTO `system_settings` (`id`, `category`, `setting_key`, `setting_value`, `default_value`, `data_type`, `description`, `validation_rules`, `is_required`, `created_at`, `updated_at`) VALUES ('22', 'Logging', 'log_retention_days', '90', '90', 'integer', 'Number of days to retain log files', '{\"required\": true, \"min_value\": 7, \"max_value\": 365}', '1', '2026-01-06 08:28:16', '2026-01-06 08:28:16');
INSERT INTO `system_settings` (`id`, `category`, `setting_key`, `setting_value`, `default_value`, `data_type`, `description`, `validation_rules`, `is_required`, `created_at`, `updated_at`) VALUES ('23', 'Logging', 'audit_enabled', 'true', 'true', 'boolean', 'Enable audit logging for sensitive operations', '{\"required\": true}', '1', '2026-01-06 08:28:16', '2026-01-06 08:28:16');
INSERT INTO `system_settings` (`id`, `category`, `setting_key`, `setting_value`, `default_value`, `data_type`, `description`, `validation_rules`, `is_required`, `created_at`, `updated_at`) VALUES ('24', 'Logging', 'audit_retention_days', '365', '365', 'integer', 'Number of days to retain audit log entries', '{\"required\": true, \"min_value\": 90, \"max_value\": 2555}', '1', '2026-01-06 08:28:16', '2026-01-06 08:28:16');
INSERT INTO `system_settings` (`id`, `category`, `setting_key`, `setting_value`, `default_value`, `data_type`, `description`, `validation_rules`, `is_required`, `created_at`, `updated_at`) VALUES ('25', 'Performance', 'cache_enabled', 'true', 'true', 'boolean', 'Enable application caching', '{\"required\": true}', '1', '2026-01-06 08:28:16', '2026-01-06 08:28:16');
INSERT INTO `system_settings` (`id`, `category`, `setting_key`, `setting_value`, `default_value`, `data_type`, `description`, `validation_rules`, `is_required`, `created_at`, `updated_at`) VALUES ('26', 'Performance', 'cache_ttl', '3600', '3600', 'integer', 'Cache time-to-live in seconds (default: 1 hour)', '{\"required\": true, \"min_value\": 300, \"max_value\": 86400}', '1', '2026-01-06 08:28:16', '2026-01-06 08:28:16');
INSERT INTO `system_settings` (`id`, `category`, `setting_key`, `setting_value`, `default_value`, `data_type`, `description`, `validation_rules`, `is_required`, `created_at`, `updated_at`) VALUES ('27', 'Performance', 'query_timeout', '30', '30', 'integer', 'Database query timeout in seconds', '{\"required\": true, \"min_value\": 5, \"max_value\": 300}', '1', '2026-01-06 08:28:16', '2026-01-06 08:28:16');
INSERT INTO `system_settings` (`id`, `category`, `setting_key`, `setting_value`, `default_value`, `data_type`, `description`, `validation_rules`, `is_required`, `created_at`, `updated_at`) VALUES ('28', 'Performance', 'max_upload_size', '10485760', '10485760', 'integer', 'Maximum file upload size in bytes (default: 10MB)', '{\"required\": true, \"min_value\": 1048576, \"max_value\": 104857600}', '1', '2026-01-06 08:28:16', '2026-01-06 08:28:16');
INSERT INTO `system_settings` (`id`, `category`, `setting_key`, `setting_value`, `default_value`, `data_type`, `description`, `validation_rules`, `is_required`, `created_at`, `updated_at`) VALUES ('2234', 'Test', 'test_model_verification', 'initial_value', 'default_value', 'string', 'Test setting for model verification', '{\"max_length\":50}', '0', '2026-01-06 08:41:02', '2026-01-06 12:25:10');
INSERT INTO `system_settings` (`id`, `category`, `setting_key`, `setting_value`, `default_value`, `data_type`, `description`, `validation_rules`, `is_required`, `created_at`, `updated_at`) VALUES ('2936', 'Email', 'test_batch_setting_8WMzTNNl', '_7Wb-PnFMIb', 'otBP5V', 'string', 'Test setting for batch validation atomicity test', '{\"min_length\":2,\"max_length\":20,\"pattern\":\"^[a-zA-Z0-9_-]+$\"}', '1', '2026-01-06 09:11:44', '2026-01-06 09:11:44');
INSERT INTO `system_settings` (`id`, `category`, `setting_key`, `setting_value`, `default_value`, `data_type`, `description`, `validation_rules`, `is_required`, `created_at`, `updated_at`) VALUES ('2937', 'Security', 'test_batch_setting_9xHvnXth', 'qh', 'DbMDEm4Yey8tGdJH', 'string', 'Test setting for batch validation atomicity test', '{\"min_length\":2,\"max_length\":20,\"pattern\":\"^[a-zA-Z0-9_-]+$\"}', '1', '2026-01-06 09:11:44', '2026-01-06 09:11:44');
INSERT INTO `system_settings` (`id`, `category`, `setting_key`, `setting_value`, `default_value`, `data_type`, `description`, `validation_rules`, `is_required`, `created_at`, `updated_at`) VALUES ('2938', 'General', 'test_batch_setting_rnnslBE6', 'false', 'false', 'boolean', 'Test setting for batch validation atomicity test', '[]', '0', '2026-01-06 09:11:44', '2026-01-06 09:11:44');
INSERT INTO `system_settings` (`id`, `category`, `setting_key`, `setting_value`, `default_value`, `data_type`, `description`, `validation_rules`, `is_required`, `created_at`, `updated_at`) VALUES ('2939', 'General', 'test_batch_setting_XmBpON47', 'C8', 'LXxoutEiQ2U', 'string', 'Test setting for batch validation atomicity test', '{\"min_length\":2,\"max_length\":20,\"pattern\":\"^[a-zA-Z0-9_-]+$\"}', '0', '2026-01-06 09:11:44', '2026-01-06 09:11:44');
INSERT INTO `system_settings` (`id`, `category`, `setting_key`, `setting_value`, `default_value`, `data_type`, `description`, `validation_rules`, `is_required`, `created_at`, `updated_at`) VALUES ('2940', 'Email', 'test_batch_setting_tyQTw5ga', 'vNe0SLISbxG6hR-', '6o', 'string', 'Test setting for batch validation atomicity test', '{\"min_length\":2,\"max_length\":20,\"pattern\":\"^[a-zA-Z0-9_-]+$\"}', '1', '2026-01-06 09:11:44', '2026-01-06 09:11:44');
INSERT INTO `system_settings` (`id`, `category`, `setting_key`, `setting_value`, `default_value`, `data_type`, `description`, `validation_rules`, `is_required`, `created_at`, `updated_at`) VALUES ('2941', 'Email', 'test_batch_setting_oEBVVoly', '0', '0', 'boolean', 'Test setting for batch validation atomicity test', '[]', '1', '2026-01-06 09:11:44', '2026-01-06 09:11:44');
INSERT INTO `system_settings` (`id`, `category`, `setting_key`, `setting_value`, `default_value`, `data_type`, `description`, `validation_rules`, `is_required`, `created_at`, `updated_at`) VALUES ('2942', 'Security', 'test_batch_setting_xGrAduQs', '8', '52', 'integer', 'Test setting for batch validation atomicity test', '{\"min_value\":1,\"max_value\":100}', '0', '2026-01-06 09:11:44', '2026-01-06 09:11:44');

SET FOREIGN_KEY_CHECKS = 1;
